import { useEffect, useState } from 'react';
import { getManagerAlerts } from '../../api/manager';
import { capitalize, formatDateTime } from '../../utils/format';
import type { ManagerAlert } from '../../types';

export default function ManagerIntelligence() {
  const [alerts, setAlerts] = useState<ManagerAlert[]>([]);
  const [loading, setLoading] = useState(true);
  const [typeFilter, setTypeFilter] = useState('');
  const [severityFilter, setSeverityFilter] = useState('');

  useEffect(() => {
    getManagerAlerts().then(setAlerts).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const filtered = alerts.filter(a => {
    if (typeFilter && a.alert_type !== typeFilter) return false;
    if (severityFilter && a.severity !== severityFilter) return false;
    return true;
  });

  const getSeverityBadge = (s: string) => {
    if (s === 'CRITICAL') return 'badge-danger';
    if (s === 'HIGH') return 'badge-warning';
    if (s === 'MEDIUM') return 'badge-info';
    return 'badge-muted';
  };

  if (loading) return <div className="page-loading"><div className="spinner" /></div>;

  return (
    <>
      <div className="page-header">
        <h1>Manager Intelligence</h1>
        <p>{alerts.length} intelligence alerts generated by agents</p>
      </div>

      <div style={{ display: 'flex', gap: 'var(--space-3)', marginBottom: 'var(--space-5)' }}>
        <select className="table-filter" value={typeFilter} onChange={e => setTypeFilter(e.target.value)}>
          <option value="">All Types</option>
          {['MANAGER_ALERT', 'ESCALATION', 'ACHIEVEMENT', 'COACHING_RECOMMENDATION', 'OPPORTUNITY_RISK'].map(t => (
            <option key={t} value={t}>{capitalize(t)}</option>
          ))}
        </select>
        <select className="table-filter" value={severityFilter} onChange={e => setSeverityFilter(e.target.value)}>
          <option value="">All Severities</option>
          {['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'].map(s => (
            <option key={s} value={s}>{s}</option>
          ))}
        </select>
      </div>

      {filtered.length === 0 ? (
        <div className="panel"><div className="panel-body empty-state"><div className="empty-state-icon">⚡</div><h3>No Alerts</h3><p>Intelligence agents haven't generated any alerts matching your filters.</p></div></div>
      ) : filtered.map(a => (
        <div key={a.alert_id} className="alert-card">
          <div className="alert-card-header">
            <div>
              <span className="alert-card-title">{a.title}</span>
              <div style={{ marginTop: '4px', display: 'flex', gap: 'var(--space-2)' }}>
                <span className={`badge ${getSeverityBadge(a.severity)}`}>{a.severity}</span>
                <span className="badge badge-muted">{capitalize(a.alert_type)}</span>
              </div>
            </div>
            <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--color-text-muted)', whiteSpace: 'nowrap' }}>{formatDateTime(a.created_at)}</span>
          </div>
          <div className="alert-card-body">
            <p>{a.summary}</p>
            {a.impact && <p style={{ marginTop: 'var(--space-2)' }}><strong>Impact:</strong> {a.impact}</p>}
          </div>
          <div className="alert-card-footer" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span>RM: <span style={{ fontFamily: 'monospace' }}>{a.rm_id.slice(0, 16)}</span></span>
            {a.recommended_action && (
              <span style={{ color: 'var(--color-accent)', fontSize: 'var(--font-size-xs)' }}>
                Action: {a.recommended_action.slice(0, 80)}{a.recommended_action.length > 80 ? '...' : ''}
              </span>
            )}
          </div>
        </div>
      ))}
    </>
  );
}
